-- 타임테이블 신청을 기존 applicants 테이블과 분리합니다.
create table if not exists public.interview_applications (
  id bigint generated by default as identity primary key,
  student_id text not null,
  name text not null,
  slot_id text not null,
  updated_at timestamptz not null default now(),
  constraint interview_applications_student_unique unique (student_id, name)
);

create index if not exists interview_applications_slot_id_idx
  on public.interview_applications (slot_id);

alter table public.interview_applications enable row level security;

-- 공개 사이트에서 시간표 현황을 읽을 수 있도록 허용
create policy "Allow public read interview applications"
on public.interview_applications
for select
to anon, authenticated
using (true);

-- 현재 프론트/API 구조와의 호환을 위해 공개 INSERT도 허용합니다.
-- 실제 신청 저장은 서버 API의 service role을 통해 처리합니다.
create policy "Allow public insert interview applications"
on public.interview_applications
for insert
to anon, authenticated
with check (true);
