-- 타임테이블 신청 데이터를 기존 applicants 테이블과 분리합니다.
-- 기존 applicants 테이블의 name/preferences 데이터에는 영향을 주지 않습니다.

create table if not exists public.interview_applications (
  id bigint generated by default as identity primary key,
  student_id text not null,
  name text not null,
  slot_id text not null,
  updated_at timestamptz not null default now(),
  constraint interview_applications_student_unique unique (student_id, name)
);

create index if not exists interview_applications_slot_id_idx
  on public.interview_applications (slot_id);

alter table public.interview_applications enable row level security;

create policy "Allow public read interview applications"
on public.interview_applications
for select
to anon, authenticated
using (true);

create policy "Allow public insert interview applications"
on public.interview_applications
for insert
to anon, authenticated
with check (true);
